### ISSUE TITLE
`continue` in `repeat` loop gives invalid code

### ISSUE THREAD

**Issue by pavelxdd** [pigpigyyy/Yuescript#102]
Lua language allows checking local variables from `repeat` loop in `until` statement:

When `continue` is used in `repeat` loop in yuescript, invalid code is generated:
````moonscript
x = 0
repeat
  x += 1
  y = x
  continue if x < 5
  print y
until y == 10
````

generated lua:
````lua
local x = 0
repeat
  local _continue_0 = false
  repeat
    x = x + 1
    local y = x
    if x < 5 then
      _continue_0 = true
      break
    end
    print(y)
    _continue_0 = true
  until true
  if not _continue_0 then
    break
  end
until y == 10
````

`y` is defined in nested `repeat` loop in generated code and is invisible for `until y == 10` check, so the loop will never return.

**Comment by pigpigyyy** [comment]
Made a new commit for `continue` used in `repeat`.
```moonscript
x = 0
repeat
  x += 1
  y = x
  continue if x < 5
  print y
until y == 10
```
now compiles to:
```lua
local x = 0
repeat
  local _cond_0 = false
  local _continue_0 = false
  repeat
    x = x + 1
    local y = x
    if x < 5 then
      _continue_0 = true
      break
    end
    print(y)
    _cond_0 = y == 10
    _continue_0 = true
  until true
  if not _continue_0 then
    break
  end
until _cond_0
```

**Comment by pavelxdd** [comment]
````moonscript
x = 0
repeat
  x += 1
  y = x
  continue if x < 5
  print y
until y > 0
````

`continue` currently skips the `until` check completely. Shouldn't the above loop exit on the first iteration without printing anything?

**Comment by pavelxdd** [comment]
`while` + `continue` generates 2 times `_continue_0 = true` around `break`.

`while true do continue`:
````lua
while true do
    local _continue_0 = false
    repeat
        _continue_0 = true
        break
        _continue_0 = true
    until true
    if not _continue_0 then
        break
    end
end
````

**Comment by pigpigyyy** [comment]
> ```moonscript
> x = 0
> repeat
>   x += 1
>   y = x
>   continue if x < 5
>   print y
> until y > 0
> ```
> 
> `continue` currently skips the `until` check completely. Shouldn't the above loop exit on the first iteration without printing anything?

I just forgot about the control flow check.
Tried to make it work this way.
```lua
local x = 0
repeat
  local _cond_0 = false
  local _continue_0 = false
  repeat
    x = x + 1
    local y = x
    if x < 5 then
      _cond_0 = y > 0
      _continue_0 = true
      break
    end
    print(y)
    _cond_0 = y > 0
    _continue_0 = true
  until true
  if not _continue_0 then
    break
  end
until _cond_0
```

> `while` + `continue` generates 2 times `_continue_0 = true` around `break`.
> 
> `while true do continue`:
> 
> ```lua
> while true do
>     local _continue_0 = false
>     repeat
>         _continue_0 = true
>         break
>         _continue_0 = true
>     until true
>     if not _continue_0 then
>         break
>     end
> end
> ```

The extra `_continue_0 = true` is used for implementing the `break` keyword when both `continue` and `break` being used in a loop.
```moonscript
while cond
  continue if condA
  break if condB
  print "work"
```
compiles to:
```lua
while cond do
  local _continue_0 = false
  repeat
    if condA then
      _continue_0 = true
      break
    end
    if condB then
      break
    end
    print("work")
    _continue_0 = true
  until true
  if not _continue_0 then
    break
  end
end
```

**Comment by pavelxdd** [comment]
````moonscript
x = 0
repeat
    x += 1
    continue if x < 5
    y = x
    print y
until y == 10
````

what about this one? `_conf_0` checks `y` before it is defined in the loop.

**Comment by pigpigyyy** [comment]
Seems to generate the expected result.
```lua
local x = 0
repeat
  local _cond_0 = false
  local _continue_0 = false
  repeat
    x = x + 1
    if x < 5 then
      _cond_0 = y == 10 -- continue and get the until check before y declared
      _continue_0 = true
      break
    end
    local y = x
    print(y)
    _cond_0 = y == 10
    _continue_0 = true
  until true
  if not _continue_0 then
    break
  end
until _cond_0
```
