### ISSUE TITLE
`const @ = ` is not a valid expression

### ISSUE THREAD

**Issue by pavelxdd** [pigpigyyy/Yuescript#103]
While it is possible to create and assign a local `self` variable:

````moonscript
@ = 123
````
compiles to `local self = 123`

These lines yuescript can't compile:

````moonscript
local @ = 123
const @ = 123
close @ = 123
````

**Comment by pigpigyyy** [comment]
`@ = 123` is an implicit way to declare either local or global variables.
```moonscript
do
  global *
  @ = 123 -- create a global

do
  local *
  @ = 123 -- create a local
```
So I think it is OK that we can not use the aliasing name `@` in the explicit ways to declare variable.
```moonscript
global @ = 123
local @ = 123
const @ = 123
close @ = 123
```
