### ISSUE TITLE
Please support 'with' block access with '[key]' syntax

### ISSUE THREAD

**Issue by thesolitudeofnoblesoul** [pigpigyyy/Yuescript#105]
Current `with` block only support `.key` and `\key`. It is kind of useful but is limited only to the const key.
I would love if YueScript make 'with' support variable key `[key]`. It would very helpful to reduce typing variable names.

Thanks and regards!

**Comment by pigpigyyy** [comment]
Got feature added.
```moonscript
with tb
  [1] = [2]\func!
  print [3]
  with [abc]
    [4] = 1
  [] = "abc"
```
now compile to
```lua
local _with_0 = tb
_with_0[1] = _with_0[2]:func()
print(_with_0[3])
do
  local _with_1 = _with_0[abc]
  _with_1[4] = 1
end
_with_0[#_with_0 + 1] = "abc"
```

**Comment by thesolitudeofnoblesoul** [comment]
Done!
Thanks you very much!
