### ISSUE TITLE
Can't exit REPL with CTRL+Z

### ISSUE THREAD

**Issue by ChildishGiant** [pigpigyyy/Yuescript#107]
**Platform:** Linux
**Description:**
When in repl (`yue`) Ctrl+z prints a replacement character instead of pausing the job 
![image](https://user-images.githubusercontent.com/13716824/179754115-d61165bf-6f9d-411b-8ba3-dae17f632729.png)

**Comment by pigpigyyy** [comment]
Ctrl+z should work like Ctrl+d now.
