### ISSUE TITLE
lua version

### ISSUE THREAD

**Issue by laoshaw** [pigpigyyy/Yuescript#109]
could not find any info regarding lua version support, which lua version is supported by yuescript, can I change that, does it matter to yuescript.

**Comment by pigpigyyy** [comment]
Yuescript support Lua 5.1 - 5.4 and also Luajit. And Yuescript compiler tool is generating codes with the embedded Lua version by default. You can change the behavior by add option `--target=5.1/5.2/5.3/5.4` to generate to other Lua version codes and detect different Lua version errors.
```sh
$ yue --target=5.1 init.yue
```
And you can also change the compiler option at compile time using macro functions.
```moonscript
$->
  import "yue"
  yue.options.target = "5.1"

-- the following codes will raise compile time errors
goto label
::label::
```
