### ISSUE TITLE
Classes dont inherits metamethods properly 

### ISSUE THREAD

**Issue by kithf** [pigpigyyy/Yuescript#114]
Seems that when the child extend the parent, it does some strange things? 
Tested on https://yuescript.org/try/ and LuaJIT 2.1.0-beta3 results are the same.
![image](https://user-images.githubusercontent.com/46825856/200402251-968e5f20-bf7e-44e4-b3ed-ef8929e8b65e.png)

Code to reproduce:
```moon
class A
  <tostring>: => return "321"
  
class B extends A

a, b = A!, B!

print tostring a -- 312
print tostring b -- table: ...
print getmetatable(b).__tostring, -- function: ...
      getmetatable(b).__tostring(b) -- 312
```

**Comment by pigpigyyy** [comment]
It's the Lua rule that only does raw-get to access the metamethods. I updated the generated codes to insert super metamethods into derived class object.
