### ISSUE TITLE
Feature request: chaining assignment

### ISSUE THREAD

**Issue by pigpigyyy** [pigpigyyy/Yuescript#115]
```moonscript
a = b = c = d = e = 0

x = y = z = f!
```

would be nice for initializing a lot of values to the same value
dunno about other languages, but python has this

could compile to:
```lua
local a = 0
local b = a
local c = a
local d = a
local e = a

local x = f()
local y = x
local z = x
```
or
```lua
local a, b, c, d, e
do
  local _temp_0 = 0
  a, b, c, d, e = _temp_0, _temp_0, _temp_0, _temp_0, _temp_0,
end
```

**Comment by GokuHiki** [comment]
Maybe YueScript should remove the extra scope because it makes code very bad for performance.
There is no need for the extra scope here.
EX:
```MoonScript
x = y = z = f!
```
Compiles to:
```Lua
local x = f()
local y = x
local z = x
```
Or maybe:
```Lua
local x = f()
local y, z = x, x -- don't know if this is faster or not
```
What do you think?
Thanks and regards!

**Comment by chrsm** [comment]
Have you tested this? I don't see how this could be slow outside of the `f()` call.

**Comment by pigpigyyy** [comment]
> 
> Maybe YueScript should remove the extra scope because it makes code very bad for performance.
> There is no need for the extra scope here.
> EX:
> ```MoonScript
> x = y = z = f!
> ```
> Compiles to:
> ```Lua
> local x = f()
> local y = x
> local z = x
> ```
> Or maybe:
> ```Lua
> local x = f()
> local y, z = x, x -- don't know if this is faster or not
> ```
> What do you think?
> Thanks and regards!
> 

It is a case for optimization I will be looking into it soon.

**Comment by pigpigyyy** [comment]
Got optimization added in 8d36b240cd0800bd5584d52cb5d19d0ae5371357.
