### ISSUE TITLE
Build fail under openresty/openresty:1.21.4.1-alpine-fat (docker image)

### ISSUE THREAD

**Issue by CriztianiX** [pigpigyyy/Yuescript#122]
Compiling: src/3rdParty/efsw/FileWatcherInotify.cpp -> build/release/3rdParty/efsw/FileWatcherInotify.o
src/3rdParty/efsw/FileWatcherInotify.cpp: In member function 'void efsw::FileWatcherInotify::run()':
src/3rdParty/efsw/FileWatcherInotify.cpp:313:9: error: 'u_int32_t' was not declared in this scope; did you mean 'uint32_t'?
  313 |         u_int32_t currentMoveCookie = -1;
      |         ^~~~~~~~~
      |         uint32_t
src/3rdParty/efsw/FileWatcherInotify.cpp:318:17: error: 'fd_set' was not declared in this scope
  318 |                 fd_set rfds;
      |                 ^~~~~~
src/3rdParty/efsw/FileWatcherInotify.cpp:319:27: error: 'rfds' was not declared in this scope
  319 |                 FD_ZERO( &rfds );
      |                           ^~~~
src/3rdParty/efsw/FileWatcherInotify.cpp:319:17: error: 'FD_ZERO' was not declared in this scope; did you mean 'NZERO'?
  319 |                 FD_ZERO( &rfds );
      |                 ^~~~~~~
      |                 NZERO
src/3rdParty/efsw/FileWatcherInotify.cpp:320:17: error: 'FD_SET' was not declared in this scope; did you mean 'L_SET'?
  320 |                 FD_SET( mFD, &rfds );
      |                 ^~~~~~
      |                 L_SET
src/3rdParty/efsw/FileWatcherInotify.cpp:321:17: error: 'timeval' was not declared in this scope
  321 |                 timeval timeout;
      |                 ^~~~~~~
src/3rdParty/efsw/FileWatcherInotify.cpp:322:17: error: 'timeout' was not declared in this scope; did you mean 'timer_t'?
  322 |                 timeout.tv_sec = 0;
      |                 ^~~~~~~
      |                 timer_t
src/3rdParty/efsw/FileWatcherInotify.cpp:325:30: error: 'FD_SETSIZE' was not declared in this scope; did you mean 'CPU_SETSIZE'?
  325 |                 if ( select( FD_SETSIZE, &rfds, NULL, NULL, &timeout ) > 0 ) {
      |                              ^~~~~~~~~~
      |                              CPU_SETSIZE
src/3rdParty/efsw/FileWatcherInotify.cpp:325:22: error: 'select' was not declared in this scope
  325 |                 if ( select( FD_SETSIZE, &rfds, NULL, NULL, &timeout ) > 0 ) {
      |                      ^~~~~~
src/3rdParty/efsw/FileWatcherInotify.cpp:347:84: error: 'currentMoveCookie' was not declared in this scope; did you mean 'currentMoveFrom'?
  347 |                                                                  pevent->cookie == currentMoveCookie ) {
      |                                                                                    ^~~~~~~~~~~~~~~~~
      |                                                                                    currentMoveFrom
src/3rdParty/efsw/FileWatcherInotify.cpp:391:25: error: 'currentMoveCookie' was not declared in this scope; did you mean 'currentMoveFrom'?
  391 |                         currentMoveCookie = -1;
      |                         ^~~~~~~~~~~~~~~~~
      |                         currentMoveFrom
make[1]: *** [makefile:322: build/release/3rdParty/efsw/FileWatcherInotify.o] Error 1
make: *** [makefile:192: release] Error 2

```
bash-5.1# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/11.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-11.2.1_git20220219/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --with-pkgversion='Alpine 11.2.1_git20220219' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada,jit --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --enable-host-shared --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220219 (Alpine 11.2.1_git20220219)

bash-5.1# make -v
GNU Make 4.3
```

**Comment by pigpigyyy** [comment]
The Yuescript compiler tool is using inotify related libs on Linux. The alpine Linux may not be with it by default. I added a make option c1cc934e55ca88117599121841301783d29aac32 to build yue without file watcher function. You could have a try with `make NO_WATCHER=true`.

**Comment by CriztianiX** [comment]
Works fine.
Thanks.
