### ISSUE TITLE
Use UNIX-style line endings on non-windows platforms.

### ISSUE THREAD

**Issue by SkyyySi** [pigpigyyy/Yuescript#131]
Functions such as `yue.traceback` currently use DOS-style line endings (`"\r\n"`). On platforms like Linux, it should use UNIX-style line endings instead (`"\n"`).

Since there's not really any reason for the UNIX version to ever use the DOS format, this can probably just be done through a macro at compile time.

**Comment by pigpigyyy** [comment]
The `"\r\n"` was added by an included 3rd-party Lua lib named StackTracePlus. Got the useless `\r` characters removed by 0a55542c9a2eb958afe4fc6797b5400902c1e058.
