### ISSUE TITLE
$FILE macro does not escape backslash (on Windows)

### ISSUE THREAD

**Issue by johnd0e** [pigpigyyy/Yuescript#135]
https://yuescript.org/doc/#builtin-macro

```
[string "C:\Temp\test.yue"]:1: invalid escape sequence near '"C:'
```

**Comment by pigpigyyy** [comment]
Made a new commit fixing this, and it seems the commit message is recognized by Github to close the issue automatically. I think issues should be closed manually in case it is not really fixed or need further discussion.

**Comment by johnd0e** [comment]
Thank you, the issue is gone.
