### ISSUE TITLE
Multiline comment error with new line

### ISSUE THREAD

**Issue by GokuHiki** [pigpigyyy/Yuescript#137]
I found that Yuescript error when multiline comment have new line
```moonscript
--[

--]
-- Work!

--[comment

--]
-- Work!

--[
comment
--]
-- Error!
```
Can you fix that!
Thanks and regards!

**Comment by pigpigyyy** [comment]
The multiline comment syntax should be using double brackets:
```lua
--[[

--]]
-- Work!

--[[comment

--]]
-- Work!

--[[
comment
--]]
```
You can see reference from here. https://yuescript.org/doc/#comment

**Comment by GokuHiki** [comment]
I see! It is my mistake!
