### ISSUE TITLE
[feature request] import ... from "string"

### ISSUE THREAD

**Issue by SkyyySi** [pigpigyyy/Yuescript#149]
I think it would be useful to allow to write:

```moonscript
import x, y, z from "mymodule"
```

... which would implicitly call `require()`:

```lua
local x, y, z
do
  local _obj_0 = require("mymodule")
  x, y, z = _obj_0.x, _obj_0.y, _obj_0.z
end
```

The current behavior is to try to index into the string literal. Since there isn't really a reason to do that, I believe that making it use `require()` automatically would be an improvement.

**Comment by pigpigyyy** [comment]
It makes sense, added it with tests and docs. And I removed the syntax of `import from` Lua string or string interpolation, so that we can ensure it to be static import for further compiler checking.

**Comment by GokuHiki** [comment]
I do a significant amount of Python programming. Can you make it support revert 'from x import y' like python. EX:
```moonscript
from logging import debug, info, warn 
```
This can help me in avoiding silly errors and can comfortably work with 2 languages ​​at the same time.

**Comment by pigpigyyy** [comment]
> ```moonscript
> from logging import debug, info, warn 
> ```

Added Python style import syntax since "from" is a keyword in Yuescript and this won't conflict with other syntax.
