### ISSUE TITLE
Error with syntax 'from module import member'

### ISSUE THREAD

**Issue by GokuHiki** [pigpigyyy/Yuescript#153]
I have the code that have the error:
```moonscript
from CS import
  System
  UnityEngine

from UnityEngine import
  Object
  GameObject
  Transform
  MonoBehaviour
  Vector3
  Quaternion

speed = 10  -- Error: syntax error
```

I Don't know what cause this error but I can bypass this error by changing `speed = 10` -> `local speed = 10`.

Hope you can fix this error soon. Thanks for your hard work.

**Comment by pigpigyyy** [comment]
Missed the rule that the item list after `from ... import` should be in an indented block. Or the parser won't be able to tell when the item list ends. Should be fixed by the new commit.

**Comment by GokuHiki** [comment]
Confirm fixed!

Thanks you very much and regards!
