### ISSUE TITLE
在Win10上安装不了呢，请帮忙看下什么问题？

### ISSUE THREAD

**Issue by world100** [pigpigyyy/Yuescript#154]
在Win10上安装不了呢，请帮忙看下什么问题？
![image](https://github.com/pigpigyyy/Yuescript/assets/4382414/ef142c45-ad8b-4556-88a8-608aa7779c92)
尝试增加环境变量也不行
![image](https://github.com/pigpigyyy/Yuescript/assets/4382414/45c49f44-ccde-4d13-b53a-bd07f76d7440)

**Comment by world100** [comment]
先去release下载了个yue.exe可以用着

**Comment by pigpigyyy** [comment]
看起来是cmake找不到Lua的链接库。建议你使用WSL的Linux环境来做编译比较好，或者用Visual Studio编译win-build目录下面的工程。再或者用Release的yue.exe也是有完整的功能的。
