### ISSUE TITLE
如何导入和使用c和c++里的类型和函数，和原生lua的步骤一样吗？

### ISSUE THREAD

**Issue by wu162** [pigpigyyy/Yuescript#167]
如何导入和使用c和c++里的类型和函数，和原生lua的步骤一样吗？

**Comment by pigpigyyy** [comment]
是的，向Lua环境导入C和C++的函数和对象可以看看这个项目：https://github.com/ThePhD/sol2。Yuescript只负责帮你简化和提升编写Lua代码的体验。

**Comment by wu162** [comment]
> 是的，向Lua环境导入C和C++的函数和对象可以看看这个项目：https://github.com/ThePhD/sol2 。Yuescript只负责帮你简化和提升编写Lua代码的体验。

感谢，了解了
