### ISSUE TITLE
[Syntax idea] Optional nil before commas

### ISSUE THREAD

**Issue by evandrodacs** [pigpigyyy/Yuescript#168]
Hi!

Is it possible to make `nil` optional before a comma in `return` and func args `(...)`?

Example:

```moonscript
fn(, c, d)
return , 2, 3,, 4
```

Compiles to:

```lua
fn(nil, c, d)
return nil, 2, 3, nil, 4
```

Thanks in advance!

**Comment by pigpigyyy** [comment]
It is possible but is it just for saving some typing? Do you have more usages or cases to show the advantage for the new syntax?

**Comment by pigpigyyy** [comment]
Guess the downside could be the idiom of "explicit is better than implicit"?

**Comment by evandrodacs** [comment]
Indeed! It can also be misinterpreted as an error, making it difficult to read. e.g.:

```lua
return,3
```
It also requires the 'return' keyword
