### ISSUE TITLE
feature request: block scoped macros

### ISSUE THREAD

**Issue by Le0Developer** [pigpigyyy/Yuescript#175]
## why

Yuepack which I developed in response to #173 puts all imported file in `do` blocks, as such macros in them sadly don't work.

## example code

```moon
do
  macro test = -> "123"
  print $test
```

## current behavior

compilation error
```
2: can not define macro outside the root block
  macro test = -> "123"
```

## expected behavior

a block scoped macro

## interesting workaround

macro **imports** *do* work in nested blocks

```moon
-- main.yue
do
  import "macros" as $
  print $test

-- macros.yue
export macro test = -> "123"
```

although they arent bound to the block and leak upwards
```moon
do
  import "macros" as $

print $test -- still works
```

**Comment by pigpigyyy** [comment]
Implementing the macro system in the root block in a module was just for simpler coding, but now the block-scope-aware macro system was done in the newer commit. So that you can now write a "local macro", and importing "macros" in the block scope.

**Comment by Le0Developer** [comment]
Thanks! seems to be working perfectly!
