### ISSUE TITLE
Reference manual

### ISSUE THREAD

**Issue by CriztianiX** [pigpigyyy/Yuescript#20]
Hi, IMO, I believe that for the language to reach many enthusiasts, moonplus should have some type of reference manual, especially detailing the improvements and new features over moonscript.
Are there any idea in roadmap?

**Comment by pigpigyyy** [comment]
Yes, reference manual is required for Moonplus. The main problem is that I'm still not sure about the Moonplus is just another tool for the Moonscript or an updated version for the language or even a language derived from Moonscript. I'm a fun for the Moonscript for many years. Just want the language to become better and helpful.

**Comment by turbo** [comment]
I think the analogy would be the JavaScript -> CoffeeScript -> LiveScript evolution. MoonScript is to Lua what CoffeeScript is/was to JavaScript. And MoonPlus is to MoonScript what LiveScript is/was to CoffeeScript. I think porting the tl typechecker (see https://github.com/pigpigyyy/MoonPlus/issues/15) would serve as MoonPlus's "killer feature", so MoonScript users can migrate to something more safe *and* more expressive (because as LiveScript has shown, it's not enough *just* to be more expressive)

**Comment by CriztianiX** [comment]
@turbo yes, you're right. Porting the tl sounds great, and this would start a new language derived from moonscript.

**Comment by ngocgodwar** [comment]
Well... MoonScript is ~~DEAD~~ STOPPED. MoonPlus need constant move forward or will be forget. But to where? There are some options worth considering:
+ Improve/Add more syntax features borrow from similar lang with great syntax like LiveScript, nim, GDScript, python. A Simple&Safe choice that will keep many fans of moonscript/coffescript happy. That will make MoonPlus constant improve, adapt and give language a sense of a living creature, not like a dead cold stone like MoonScript!
+ Add tl typechecker. That mean: "moon -> tl -> lua". A big step and a bold move, a very nice features but not sure about "killer" part. Just think about TypeScript with out a huge commit support for IDE, Editor, lib, autocomplete helper and support from the Titan Microsoft. I don't expect any magic here. I'am not sure but I think it can make MoonPlus more complicated which is not sure attractive fans of moonscript/coffescript. But I think many will like it.
+ Imporve/Add more feature to macro/dynamic complier to lua code. And unorthodox move. Which mean give user supper power to mod, create, play with the code they created. It will make MoonPlus "distinct" from the rest. just take a look at "https://nomsu.org/". Not aim to please all but to be special for some.
+ Or maybe some effort go for IDE, Editor, Lint. But. Well... it only worth if there many MoonPlus users.

Thanks and regards~

**Comment by pigpigyyy** [comment]
Just made some effort to write a reference site for this project. Wish we can keep pushing the project to go further. http://yuescript.org

**Comment by CriztianiX** [comment]
#48
