### ISSUE TITLE
Moonplus (.moon) file type

### ISSUE THREAD

**Issue by CriztianiX** [pigpigyyy/Yuescript#21]
Since extension  is used by moonscript I think moonplus should have an extension for itself.
Moonscript applications can be compiled using the moonplus compiler, but, moonplus applications cannot be compiled by moonscript.
in this way users could try to compile their applications without success.
so what are the chances that moonplus has its own extension, something like moonp?

**Comment by pigpigyyy** [comment]
Do you mean Moonplus should provide some compatible functions or modes to support compiling the original Moonscript codes? Currently Moonplus has made some syntax incompatible with original Moonscript. Like disabling writing expression list in the middle of a code block and removing the 'else' clause for line decorator syntax.
```Moonscript
f = ->
  1,2,3 -- valid in Moonscript but disabled in Moonplus
  true

print 1 if cond else print 2 -- valid in Moonscript but disabled in Moonplus
```

**Comment by CriztianiX** [comment]
Sorry, no, i was thinking in "file type"  (.moon).

**Comment by CriztianiX** [comment]
Since file type (.moon) is used by moonscript , I think moonplus should have an file type for itself.
Moonscript applications can be compiled using the moonplus compiler, but, moonplus applications cannot be compiled by moonscript.
in this way users could try to compile their moonscrip (.moon) applications without success.
so , what are the chances that moonplus has its own file extension, maybe something like .moonp?

**Comment by pigpigyyy** [comment]
File extension ".moonp" is OK but maybe a little bit too long. How about ".mp"? It seems that this extension does not conflict with other source files for the moment.

**Comment by CriztianiX** [comment]
It's ok for me.

**Comment by pigpigyyy** [comment]
Changed file extension to ".mp" by commit 97bbe98289fb74c7cf2d9793b80a1a27b4146045
And MoonPlus file extension can now be altered by codes:
```Lua
local moonp = require("moonp")
moonp.extension = "moonp"
moonp.require("init") -- require module by file 'init.moonp'
```

**Comment by CriztianiX** [comment]
Now we have "yue"
