### ISSUE TITLE
`moonp` does not pass command line arguments.

### ISSUE THREAD

**Issue by daelvn** [pigpigyyy/Yuescript#34]
In lua, you can have a script such as:
```lua
for k, v in pairs {...} do print k, v end
-- or --
for k, v in pairs arg do print k, v end
```
Which then you can run as `lua test.lua a b c` to get:
```
1 a
2 b
3 c
```

But, doing this with `moonp -e test.mp a b c`:
```moon
for k, v in pairs {...} do print k, v
-- or --
for k, v in pairs arg do print k, v
```

Gives you either of these errors:
```
1: cannot use '...' outside a vararg function near '...'
for k, v in pairs {...} do print k, v
# or #
test.mp:1: bad argument #1 to 'for iterator' (table expected, got nil)
```

Does `moonp` not pass CLI arguments at all?

**Comment by pigpigyyy** [comment]
Yes, moonp was not passing CLI arguments. But found the real issue was a wrong syntax check. It should be fixed by the newest commit now.
