### ISSUE TITLE
Support Chaining Function Calls?

### ISSUE THREAD

**Issue by thesolitudeofnoblesoul** [pigpigyyy/Yuescript#38]
Support Chaining Function Calls?

As a CoffeeScript user: MoonPlus work just like CoffeeScript or event better.
I love MoonScript very much but it just lack some important features.
I really mist ability to "chain function calls" and it hard to dev with out it.

Take a look at examble in CoffeeScript, it look realy nice:
```CoffeeScript
$ 'body'
.click (e) ->
  $ '.box'
  .fadeIn 'fast'
  .addClass 'show'
.css 'background', 'white'
```

I current work with Unity via xlua, it work really nice if I can code like this:
```MoonScript
origin.transform.root.gameObject\Parents!
\Descendants!
\SelectEnable!
\SelectVisible!
\TagEqual "fx"
\Where (x) -> x.name\EndsWith("(Clone)")
\Destroy!
```
I hove we can do the same in MoonPlus, can you implement it?
Thanks you very much!

**Comment by pigpigyyy** [comment]
I've been thinking of adding chaining function calls in multiline. The problem is the syntax you proposed will conflict with the 'with' statement.

**Comment by pigpigyyy** [comment]
I've been thinking of adding chaining function calls in multiline. The problem is the syntax you proposed will conflict with the 'with' statement.
```moonscript
with something
  origin.transform.root.gameObject\Parents!
  \Descendants!
  \SelectEnable!
  \SelectVisible!
  \TagEqual "fx"
  \Where (x) -> x.name\EndsWith("(Clone)")
  \Destroy!
```
Will be compiled to
```lua
origin.transform.root.gameObject:Parents()
something:Descendants()
something:SelectEnable()
something:SelectVisible()
something:TagEqual("fx")
something:Where(function(x)
  return x.name:EndsWith("(Clone)")
end)
something:Destroy()
```
But currently we can use macro function from Moon+ to do something similar.
```moonscript
macro expr chain = (...)->
  callable = nil
  for item in *{...}
    callable = callable? and "(#{callable})\\#{item}" or item
  callable

result = $chain(
  origin.transform.root.gameObject\Parents!
  Descendants!
  SelectEnable!
  SelectVisible!
  TagEqual "fx"
  Where (x) -> x.name\EndsWith "(Clone)"
  Destroy!
)

$chain(
  origin.transform.root.gameObject\Parents!
  Descendants!
  SelectEnable!
  SelectVisible!
  TagEqual "fx"
  Where (x) -> x.name\EndsWith "(Clone)"
  Destroy!
)
```
compiles to
```lua
local result = ((((((origin.transform.root.gameObject:Parents()):Descendants()):SelectEnable()):SelectVisible()):TagEqual("fx")):Where(function(x)
  return x.name:EndsWith("(Clone)")
end)):Destroy();
((((((origin.transform.root.gameObject:Parents()):Descendants()):SelectEnable()):SelectVisible()):TagEqual("fx")):Where(function(x)
  return x.name:EndsWith("(Clone)")
end)):Destroy()
```

**Comment by thesolitudeofnoblesoul** [comment]
Uhm... Honestly speaking, 'with' statement kind of a strange alien creator to me. I don't see much of it useful, it make the code look confused and very unintuitive. Well of course I don't know any language that use it concept and see nobody talk about any kind of pattern or feature similar to it.

Compare to dubious 'with' statement, "chaining function calls" in multiline is what everyone used and every langage has it as default. It just strange that nice thing like MoonPlus don't support it officially.

I think we can solve conflict simply by make MoonPlus support "chaining function calls" by default and just fallback to 'with' statement when in block of 'with'.
This way we can make MoonPlus work in both case. Not that I think people use much of 'with' statement.

Well... I just test out macro, it really powerfull... But the are some problem:

It just get error if there are any more code.
``` MoonScript
macro expr chain = (...)->
  callable = nil
  for item in *{...}
    -- print type callable
    callable = callable? and "(#{callable})\\#{item}" or item
  callable

result = $chain(
  origin.transform.root.gameObject\Parents!
  Descendants!
  SelectEnable!
  SelectVisible!
  TagEqual "fx"
  Where (x) ->
    if x\IsTargeted!
      return false
    x.name\EndsWith "(Clone)"
  Destroy!
)

$chain( -- ERROR: macro type mismatch, block expected, got expr `$chain(`
  origin.transform.root.gameObject\Parents!
  Descendants!
  SelectEnable!
  SelectVisible!
  TagEqual "fx"
  Where (x) -> x.name\EndsWith "(Clone)"
  Destroy!
)

origin.Update!
```

Well... I just make another macro as block and get it work but feel like somekind of hack.
It nice but it kind of hard to use, easy to get error. But the worst is when it error it just failed silently.
Take EX:
```MoonScript
macro expr array_allocate = (n, def) ->
  tb = {}
  for i = 1,n
    tb[#tb+1] = def or false
  "{#{table.concat(tb,',')}}" -- ERROR: but MoonPlus don't tell me about it and just crashed silently.

a = $array_allocate 10
```
Note that I am on window!

By the way, can MoonPlus clean up many redundant parentheses in lua code? it just hard to view and debug with code like this:
```Lua
local result = ((((((origin.transform.root.gameObject:Parents()):Descendants()):SelectEnable()):SelectVisible()):TagEqual("fx")):Where(function(x)
  return x.name:EndsWith("(Clone)")
end)):Destroy();
((((((origin.transform.root.gameObject:Parents()):Descendants()):SelectEnable()):SelectVisible()):TagEqual("fx")):Where(function(x)
  return x.name:EndsWith("(Clone)")
end)):Destroy()
```

Thanks for you support!

**Comment by pigpigyyy** [comment]
Thank you for trying out moon+ macros. Commit 32651cccb380bf4682fa8f6d3e70d74952171f7b should fix the macro type mismatch issue and gets the example work. The `$array_allocate` macro reports error with Lua 5.4 on OSX, maybe it's the problem from different Lua version, can you tell me how you're using MoonPlus and getting the crash?
```sh
# error messages from my moonp tool with Lua 5.4
> $ moonp --                                                                   
macro expr array_allocate = (n, def) ->
  tb = {}
  for i = 1,n
    tb[#tb+1] = def or false
  "{#{table.concat(tb,',')}}" -- ERROR: but MoonPlus don't tell me about it and just crashed silently.

a = $array_allocate 10

7: failed to expand macro: (macro array_allocate):5: invalid value (boolean) at index 1 in table for 'concat'
Stack Traceback
===============
(1) field C function 'concat'
(2) '=(macro array_allocate)':5
(3) global C function 'xpcall'
(4) '=(moonplus)':144

a = $array_allocate 10
    ^
```

**Comment by thesolitudeofnoblesoul** [comment]
Well... I just use moonp.exe compiled by VS2019 to compile to .lua file.
When it error... Nothing happened at all, I get nothing! moonp.exe just crash or freeze and I must look around know what happened and kill it from tasks manager.

About “With” statement, I remember MUST do many project in school with VAB but don't know about it. Well, it not like I have a thing for VBA anyway. I'm kind of understand why CoffeeScript remove it, guess that not many people like it anyway.
But of course it not like we can just remove it from MoonPlus but support chaining function calls on top of it would be very welcome.

Thanks!

**Comment by thesolitudeofnoblesoul** [comment]
I just make some extend check, it look like problems only with VS2019 in windows.
Cygwin, MinGW throw stack traceback is fine!
Don't know why?

Thanks!

**Comment by pigpigyyy** [comment]
Tested with VS2019 v16.8.4 and MSVC v19.28.29336, the moonp binary works as expected. Maybe it's a bug for a specified MSVC version. And I made some changes for moon+ macro and managed to write a new macro to do chaining calls.
```moonscript
macro chain = (...)->
  import "moonp" as {:to_lua}
  callable = nil
  config = {
    implicit_return_root: false
    reserve_line_number: false
  }
  for item in *{...}
    if callable?
      callable = "#{callable}:#{to_lua(item,config)\gsub '%s*$',''}"
    else
      callable = to_lua(item,config)\gsub '%s*$',''
  {
    codes: callable
    type: "lua"
  }

$chain(
  origin.transform.root.gameObject\Parents!
  Descendants!
  SelectEnable!
  SelectVisible!
  TagEqual "fx"
  Where (x) -> x.name\EndsWith "(Clone)"
  Destroy!
)

nil
```
now compiles to
```lua
origin.transform.root.gameObject:Parents():Descendants():SelectEnable():SelectVisible():TagEqual("fx"):Where(function(x)
  return x.name:EndsWith("(Clone)")
end):Destroy()
return nil
```
And I'm now considering adding a new syntax to do function call chaining, maybe by introducing a new operator?

**Comment by thesolitudeofnoblesoul** [comment]
Thanks it kind of better without that many parentheses.

About new operator for call chaining: We already have op "\" at the end to glue lines together with space. Then may be something like "\\" mean glue lines together and remove any white chars between them?

By the way, when doing chain function calls I note that MoonPlus treat literal "string" and table {} not the same as in lua.
Many syntax work on "string" not work on table {}. EX:
EX:
```MoonScript
split"abc xyz 123"\map"#"\printAll!

_ = f""[a]
_ = f""\b!
_ = f"".c!
_ = f""[a]
_ = f""\b!
_ = f"".c!

f ""[a]
f ""\b!
f "".c!
f ""[a]
f ""\b!
f "".c!

return
```
When use with literal table {}, it just not work consistently as in lua:
```MoonScript
list{"abc","xyz", "123"}\map"#"\printAll!

_ = f{}[a]
_ = f{}\b!
_ = f{}.c!
_ = f{}[a]
_ = f{}\b!
_ = f{}.c!

f {}[a]
f {}\b!
f {}.c!
f {}[a]
f {}\b!
f {}.c!

return
```
I feel it kind of inconsistent when compare to lua, maybe we can improve it?

Thanks!

**Comment by pigpigyyy** [comment]
back slash to escape new line is OK in moon+, but back slash is also treated like a space symbol for the moment.
```moonscript
tb\
func!
```
compiles to
```lua
return tb(func())
```
The inconsistent issue you mentioned is partially fixed in the newest commit.
```moonscript
list{"abc", "xyz", "123"}\map"#"\printAll!
_ = f{}[a]
_ = f{}\b!
_ = f{}.c!
```
compiles to
```lua
list({
  "abc",
  "xyz",
  "123"
}):map("#"):printAll()
local _ = f({ })[a]
_ = f({ }):b()
_ = f({ }).c()
```
But the last case of using table literal as a chain value start item, I feel it won't be that useful. And currently supporting this syntax may slow down every value expression a little. If you have any better cases of using that syntax, I can add back the syntax in later commit.

**Comment by thesolitudeofnoblesoul** [comment]
I just list all case that can thing of literal value, so I guess it ok now.

About new op black slash glue lines, I mean "double back slash".
It just typo, I forget about there are escaped in comment.
I mean we can add one more back slah or something similar that mean auto trim all lead-trail whitespace between lines.
What do you think?

Thanks!

**Comment by pigpigyyy** [comment]
I've come up with a better idea. Since Moonscript is a white space significant language, we can make use of a indent to start a new block to do multiline chaining function call. I've implement the syntax like:
```moonscript
result = origin
  .transform.root
  .gameObject
  \Parents!
  \Descendants!
  \SelectEnable!
  \SelectVisible!
  \TagEqual("fx")
  \Where (x)->
    if x\IsTargeted!
      return false
    x.name\EndsWith "(Clone)"
  \Destroy!

origin.transform.root.gameObject
  \Parents!\Descendants!
  \SelectEnable!
  \SelectVisible!
  \TagEqual "fx"
  \Where (x)-> x.name\EndsWith "(Clone)"
  \Destroy!

-- work with "with" syntax
with tb
  .x = item
    .field
    \func!
  .y = 123
```
compiles to
```lua
local result = origin.transform.root.gameObject:Parents():Descendants():SelectEnable():SelectVisible():TagEqual("fx"):Where(function(x)
  if x:IsTargeted() then
    return false
  end
  return x.name:EndsWith("(Clone)")
end):Destroy()
origin.transform.root.gameObject:Parents():Descendants():SelectEnable():SelectVisible():TagEqual("fx"):Where(function(x)
  return x.name:EndsWith("(Clone)")
end):Destroy()
tb.x = item.field:func()
tb.y = 123
return tb
```

**Comment by thesolitudeofnoblesoul** [comment]
It much better now!
