### ISSUE TITLE
Can't install yuescript using luarocks. Build error

### ISSUE THREAD

**Issue by Kiriz01** [pigpigyyy/Yuescript#42]
Hello. I'm trying to install yuescript. However, i keep getting the error.

root@komarovsergey37:~# luarocks install yuescript
Installing https://luarocks.org/yuescript-0.6.9-1.src.rock

yuescript 0.6.9-1 depends on lua >= 5.1 (5.3-1 provided by VM)
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Lua: using information from luarocks
-- LUA_LIBDIR: /usr/include/lua5.3/../lib /usr/include/lua5.3/../../lib
-- LUA_INCDIR: /usr/include/lua5.3
-- LUA: /usr/bin/lua5.3
-- Lua library: LUA_LIBRARIES-NOTFOUND
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUA_LIBRARIES
    linked by target "yue" in directory /tmp/luarocks_yuescript-0.6.9-1-uXAKw9/yuescript
    linked by target "libyue" in directory /tmp/luarocks_yuescript-0.6.9-1-uXAKw9/yuescript

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_yuescript-0.6.9-1-uXAKw9/yuescript/build.luarocks/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed cmake.

**Comment by Kiriz01** [comment]
I want to use yuescript in lua, so i have to install the package using luarocks

**Comment by pigpigyyy** [comment]
The CMake functions provided by luarocks are just looking for some regular Lua dev path. In your environment, it assumed you have put Lua executable in `/usr/bin/lua5.3`, Lua headers in `/usr/include/lua5.3` and then failed to find Lua libs in `/usr/include/lua5.3/../lib` or `/usr/include/lua5.3/../../lib`. Can you check if you really have target files under these paths? Or you can find the correct paths for these Lua staffs in your system so that I can add them as an extra case in the CMakelist.txt file.

**Comment by Kiriz01** [comment]
root@komarovsergey37:~# ls /usr/include/lua5.3
lauxlib.h  luaconf.h  lua.h  lua.hpp  lualib.h

**Comment by pigpigyyy** [comment]
Is there a liblua.a or liblua53.a in the /usr/lib/lua5.3?

**Comment by Kiriz01** [comment]
There is no lua5.3. Sorry for long reply, our timezones are different.

**Comment by pigpigyyy** [comment]
It's pefectly OK for the asynchronous interaction on the Internet and it's not an urgent problem so that we can deal with it slower. Searched the lua5.3 package info for archlinux, there is a liblua53.so ready in the path /usr/lib. I will modify the cmakelist.txt configuration to link with archlinux Lua package file in a new commit for luarocks to work.

**Comment by Kiriz01** [comment]
Thank you!

**Comment by pigpigyyy** [comment]
Tested on ArchLinux with pacman v5.2.2, yuescript seems to be installed without problems. Maybe your Lua package is not installed correctly?

```sh
# pacman -Si lua
Repository      : extra
Name            : lua
Version         : 5.4.2-1
Description     : Powerful lightweight programming language designed for extending applications
Architecture    : x86_64
URL             : https://www.lua.org/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : readline
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 277.06 KiB
Installed Size  : 1186.28 KiB
Packager        : Anatol Pomozov <anatol.pomozov@gmail.com>
Build Date      : Fri Dec  4 00:45:19 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

# pacman -Si luarocks
Repository      : community
Name            : luarocks
Version         : 3.5.0-1
Description     : Deployment and management system for Lua modules
Architecture    : any
URL             : https://luarocks.org/
Licenses        : custom
Groups          : None
Provides        : None
Depends On      : coreutils  curl  lua  unzip  zip
Optional Deps   : cvs: for fetching sources from CVS repositories
                  git: for fetching sources from git repositories
                  mercurial: for fetching sources from mercurial repositories
                  cmake: for building rocks that use the cmake build system
                  lua-sec: HTTPS support
Conflicts With  : None
Replaces        : luarocks5.1  luarocks5.2
Download Size   : 137.00 KiB
Installed Size  : 677.84 KiB
Packager        : Daurnimator <daurnimator@archlinux.org>
Build Date      : Tue Jan 26 19:56:27 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
```sh
# luarocks install yuescript
Installing https://luarocks.org/yuescript-0.7.1-1.src.rock
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Lua: using information from luarocks
-- LUA_LIBDIR: /usr/include/../lib /usr/include/../../lib
-- LUA_INCDIR: /usr/include
-- LUA: /usr/bin/lua5.4
-- Lua library: /usr/lib/liblua.so
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_yuescript-0.7.1-1-KQ574T/yuescript/build.luarocks
Scanning dependencies of target yue
[  7%] Building CXX object CMakeFiles/yue.dir/src/yuescript/ast.cpp.o
[ 15%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yue_compiler.cpp.o
[ 23%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yue_parser.cpp.o
[ 30%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yuescript.cpp.o
[ 38%] Building CXX object CMakeFiles/yue.dir/src/yuescript/parser.cpp.o
[ 46%] Building CXX object CMakeFiles/yue.dir/src/yue.cpp.o
[ 53%] Linking CXX executable yue
[ 53%] Built target yue
Scanning dependencies of target libyue
[ 61%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/ast.cpp.o
[ 69%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/parser.cpp.o
[ 76%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yue_parser.cpp.o
[ 84%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yue_compiler.cpp.o
[ 92%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yuescript.cpp.o
[100%] Linking CXX shared module yue.so
[100%] Built target libyue
[ 53%] Built target yue
[100%] Built target libyue
Install the project...
-- Install configuration: ""

yuescript 0.7.1-1 depends on lua >= 5.1 (5.4-1 provided by VM)
yuescript 0.7.1-1 is now installed in /usr (license: MIT)
```

**Comment by Kiriz01** [comment]
I'm not on ArchLinux, I'm on Ubuntu, so i typed "sudo apt-get install lua5.3".

**Comment by Kiriz01** [comment]
root@dreamy:~# luarocks install yuescript                            
Installing https://luarocks.org/yuescript-0.7.1-1.src.rock           

yuescript 0.7.1-1 depends on lua >= 5.1 (5.3-1 provided by VM)
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Lua: using information from luarocks
-- LUA_LIBDIR: /usr/include/lua5.3/../lib /usr/include/lua5.3/../../l
ib
-- LUA_INCDIR: /usr/include/lua5.3
-- LUA: /usr/bin/lua5.3
-- Lua library: /usr/lib/liblua.a
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_yuescript-0.7.1-1-
avmRqT/yuescript/build.luarocks
Scanning dependencies of target yue
[  7%] Building CXX object CMakeFiles/yue.dir/src/yuescript/ast.cpp.o
[ 15%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yue_compi
ler.cpp.o
[ 23%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yue_parse
r.cpp.o
[ 30%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yuescript
.cpp.o
[ 38%] Building CXX object CMakeFiles/yue.dir/src/yuescript/parser.cp
p.o
[ 46%] Building CXX object CMakeFiles/yue.dir/src/yue.cpp.o
[ 53%] Linking CXX executable yue
[ 53%] Built target yue
Scanning dependencies of target libyue
[ 61%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/ast.cp
p.o
[ 69%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/parser
.cpp.o
[ 76%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yue_pa
rser.cpp.o
[ 84%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yue_co
mpiler.cpp.o
[ 92%] Building CXX object CMakeFiles/libyue.dir/src/yuescript/yuescr
ipt.cpp.o
[100%] Linking CXX shared module yue.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/liblua.a
(lstate.o): relocation R_X86_64_PC32 against symbol `lua_newstate' ca
n not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/liblua.a
(lauxlib.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2
.2.5' can not be used when making a shared object; recompile with -fP
IC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/libyue.dir/build.make:145: yue.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/libyue.dir/all] Er
ror 2
make: *** [Makefile:130: all] Error 2

Error: Build error: Failed building.

I downloaded liblua.a and put the package in /usr/lib/. So i have got this error.

**Comment by Kiriz01** [comment]
I just wanna say that i tried on Ubuntu, Debian, Centos. I found the problem, but there is a new error. 
That's messed up
[root@dreamy Yuescript]luarocks make                                 Warning: Lua 5.4 interpreter not found at /root/lua-5.4.2            
Modules may not install with the correct configurations. You may want to configure the path prefix to your build of Lua 5.4 using

   luarocks config --local lua_dir <your-lua-prefix>


yuescript dev-1 depends on lua >= 5.1 (5.4-1 provided by VM)
-- Lua: using information from luarocks
-- LUA_LIBDIR: /root/lua-5.4.2/src/lib /root/lua-5.4.2/src/lib
-- LUA_INCDIR: /root/lua-5.4.2/src
-- LUA: /root/lua-5.4.2/src/lua
-- Lua library: /root/lua-5.4.2/src/liblua.a
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Yuescript/build.luarocks
[  7%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yue_compiler.cpp.o
[ 15%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yue_parser.cpp.o
[ 23%] Building CXX object CMakeFiles/yue.dir/src/yuescript/yuescript.cpp.o
[ 30%] Building CXX object CMakeFiles/yue.dir/src/yuescript/parser.cpp.o
[ 38%] Building CXX object CMakeFiles/yue.dir/src/yue.cpp.o
[ 46%] Linking CXX executable yue
CMakeFiles/yue.dir/src/yue.cpp.o: In function `main':
yue.cpp:(.text.startup+0x868): undefined reference to `pthread_create'
/root/lua-5.4.2/src/liblua.a(loadlib.o): In function `lookforfunc':
loadlib.c:(.text+0x4e2): undefined reference to `dlsym'
loadlib.c:(.text+0x546): undefined reference to `dlopen'
loadlib.c:(.text+0x5c1): undefined reference to `dlerror'
loadlib.c:(.text+0x5e1): undefined reference to `dlerror'
/root/lua-5.4.2/src/liblua.a(loadlib.o): In function `gctm':
loadlib.c:(.text+0x6cf): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/yue.dir/build.make:160: yue] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/yue.dir/all] Error 2
gmake: *** [Makefile:130: all] Error 2

Error: Build error: Failed building.
[root@dreamy Yuescript]#

**Comment by pigpigyyy** [comment]
Sorry for having messed this issue with another one related to ArchLinux. The undefined reference to `pthread_create' issue is missing the -lpthread flag for some older C++ compiler version. I'm now looking for a way to solved all the compiling and lib finding issues on all kinds of Linux package management tools. Wish I can find a final solution for all these problems.

**Comment by Kiriz01** [comment]
Thank you!🤗

**Comment by pigpigyyy** [comment]
Replaced the Lua lib locating function of luarocks with find_library function from CMake, yuescript can now be installed successfully on ubuntu 20.04. And you have to do `sudo apt install liblua5.3-dev` first.

**Comment by Kiriz01** [comment]
Thank you so much!!! It works perfectly!
Where can i learn yuescript? Is there any docs?

**Comment by pigpigyyy** [comment]
Sorry for the missing docs. Yuescript is mostly Moonscript + new features for the moment. The Moonscript docs will show many available syntax for Yuescript. It seems luvit is not searching the Lua paths on local machine. You may need to set some Lua library search paths for luvit.

**Comment by Kiriz01** [comment]
Yeah, that was first thing i did. I set luvit searching path, but i doesn't work. Anyways, thank you so much!

**Comment by Kiriz01** [comment]
I'm gonna close the issue
