### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by aergo20** [pigpigyyy/Yuescript#44]
Great project! Any chance of making the precompiled binaries available as a release? Thanks in advance!

**Comment by pigpigyyy** [comment]
Is there a reason not to compile from the sources to get the binary file? Since the size of source files can be smaller than binary file and most developer environment could have a gcc/g++ compiler tools, it won't cause much trouble compiling the binary file.

**Comment by aergo20** [comment]
My ubuntu 20 droplet has little ram (512 MB). make install causes an out-of-memory error when compiling.

**Comment by pigpigyyy** [comment]
That's a real problem. Got the github action file updated and it's now releasing the linux binary with new tag event. You may find the current binary here: https://github.com/pigpigyyy/Yuescript/releases/tag/v0.7.3

**Comment by aergo20** [comment]
Thank you for your support! I already put it on my server and it's already working!
