### ISSUE TITLE
Luvit can't require .so file.

### ISSUE THREAD

**Issue by Kiriz01** [pigpigyyy/Yuescript#45]
I get segmentation fault when i try to require yue in luvit. Moonscript works perfectly

**Comment by pigpigyyy** [comment]
Did you find the solution to fix this issue? I've tried luvit with yuescript build with lua5.1, but it kept failing to require. Guess I have to build yuescript with luajit to support luvit, but luajit is not running on my arm64 macbook so I can't test it out for the moment.
