### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gasacchi** [pigpigyyy/Yuescript#48]
Hi, recently find this repo.
will this language get documentation soon?

**Comment by pigpigyyy** [comment]
Well, where there is an issue, there should be a fix. It's a language sharing most of the features from Moonscript with lots of updates, you may start with Moonscript for the moment. And I'll be working on the docs soon.

**Comment by pigpigyyy** [comment]
Took some time to write the document site. You can now find the document from here http://yuescript.org

**Comment by gasacchi** [comment]
thank you hard work, pretty decent :100:
