### ISSUE TITLE
Community forum?

### ISSUE THREAD

**Issue by JeysonFlores** [pigpigyyy/Yuescript#53]
Hi, is there any kind of community forum like a subredit or a discord server to chat about Yuescript?
It's a nice improvement for those who wanted more features for moonscript!

**Comment by pigpigyyy** [comment]
Since there are fewer people using this project, I thought the github issue should be enough for discussing it. But setting up a discord server won't cost much effort, then I just opened one. https://discord.gg/cRJ2VAm2NV

**Comment by JeysonFlores** [comment]
Thanks!
