### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [pigpigyyy/Yuescript#56]
Hi, I was wondering what is the status of this project? 
It seems to be not particularly active but still alive, so basically are there any features/changes/removals in mind?

**Comment by pigpigyyy** [comment]
Currently you may read about the discussions under the issues. The features / changes / removals are all requested by any one who uses Yuescript and will be implemented if seen reasonable.

**Comment by gytis-ivaskevicius** [comment]
Welp, I expected some sort of vision but judging by from your response it does not seem to be any. That's a little unfortunate but ill take a look :) Thanks

**Comment by pigpigyyy** [comment]
It is an open source project. The vision is offered by any one who participates, including you. So I have no doubt that you're getting this conclusion.
