### ISSUE TITLE
Built-in minifier behaves incorrect

### ISSUE THREAD

**Issue by Nyaacinth** [pigpigyyy/Yuescript#63]
something like this:
```moonscript
aya, ber = 1, 2
print aya, ber
```
will be compiled to:
```lua
local ca=1,2;return print(c,a)
```
I think here might be `local c,a=1,2` but for some reason the compiler stitched them together incorrectly...

**Comment by pigpigyyy** [comment]
I fixed this issue in another project and forgot to update the codes in this repo.

**Comment by Nyaacinth** [comment]
fixed
