### ISSUE TITLE
Index Function Returns

### ISSUE THREAD

**Issue by Nyaacinth** [pigpigyyy/Yuescript#66]
It would be nice if we can index function returns like this:
```moonscript
{func_01!}[1]
```
That will be useful with piping operator, here's an example:

```moonscript
-- Some codes... --
-- Now we have func_01 returns two value,
-- a table and a number. func_02 has two
-- params, a table and a string with default
-- value. I want to pass the table returned by
-- func_01 to func_02 as the first param.

-- This will cause an error, because func_02 is
-- expecting a string or nil as the second param
func_01! |> func_02

-- So we need a variable here to filter the
-- first return value
rtbl = func_01!
func_02 rtbl

-- But if we can index function returns:
{func_01!}[1] |> func_02 _, "Meow"
```

**Comment by pigpigyyy** [comment]
Currently you can write valid codes as
```moonscript
({func_01!})[1] |> func_02 _, "Meow"

-- or

sel = (index, ...)->
  first = select index, ...
  first

func_01! |> sel(1, _) |> func_02 _, "Meow"
```
For your problem. Indexing a table literal might be a rare operation so that Lua and Moonscript is not implementing it.

**Comment by Nyaacinth** [comment]
> Currently you can write valid codes as
> 
> ```moonscript
> ({func_01!})[1] |> func_02 _, "Meow"
> 
> -- or
> 
> sel = (index, ...)->
>   first = select index, ...
>   first
> 
> func_01! |> sel(1, _) |> func_02 _, "Meow"
> ```
> 
> For your problem. Indexing a table literal might be a rare operation so that Lua and Moonscript is not implementing it.

Ah... I forgot that, `({func_01!})[1] |> func_02 _, "Meow"` can be used. Thanks and I will close this issue...
