### ISSUE TITLE
Refer to other class members in a class

### ISSUE THREAD

**Issue by 11clock** [pigpigyyy/Yuescript#72]
When you do something like the following:

```
class Example
  field1: 1
  field2: Example.field1 + 1
```

You get a nil pointer error on the third line since Example is nil.

**Comment by pigpigyyy** [comment]
This is an expected behavior since you can't do the same with Lua table.
```lua
local Example = {
  field1 = 1,
  field2 = Example.field1 + 1 -- Example is nil here
}
```
But with class from Yuescript you can do it in the class constructor to initialize the fields
```moonscript
class Example
  new: =>
    @field1 = 1
    @field2 = @field1 + 1
```
