### ISSUE TITLE
Implicit Objects (Documentation)

### ISSUE THREAD

**Issue by ShalokShalom** [pigpigyyy/Yuescript#75]
Hi there :)

I appreciate the extensive documentation of Yuescript

So far as I can tell, did you add 'implicit objects' new to the language

I can see it mentioned here, basically as the first feature, directly after import statements:

http://yuescript.org/doc/#introduction

But then, there is nothing mentioned in the actual documentation.

**Comment by pigpigyyy** [comment]
Sorry for missed it. Added a little doc here http://yuescript.org/doc/#implicit-object
