### ISSUE TITLE
Syntactic Sugar for pcall

### ISSUE THREAD

**Issue by 11clock** [pigpigyyy/Yuescript#80]
Using pcall for error handling is pretty awkward, especially when other languages provide try catch blocks for such purposes. I recommend syntax of a similar manner, while still providing the ability to pass in a function.

```
try
  print “Hello”
catch error_message
  print error_message

try example_function(variable)
catch error_message
  print error_message
```

Because pcall on successful execution returns whatever the function passed into it returns, I recommend another block for handling a success.

```
try function(…)
ok value1, value2, …
  …
catch e
  …
```

If you want something much lighter, the try ok catch block can make ok and catch optional, and make it an expression that returns what pcall usually returns.

```
status, value = try function(…)

status, value = try
  …
  return whatever
```

**Comment by pigpigyyy** [comment]
I like the idea. The only problem is introducing new keyword `try`. Once syntax added, we can no longer write variable named "try" in Yuescript.

**Comment by pigpigyyy** [comment]
The compiler rules could be like this?
```moonscript
try
  func 1, 2, 3
catch err
  print err

success, result = try
  func 1, 2, 3
catch err
  print err

success, result = try func 1, 2, 3

try func 1, 2, 3
catch err
  print err
```
compiles to
```lua
xpcall(function()
  return func(1, 2, 3)
end, function(err)
  print(err)
end)

local success, result = xpcall(function()
  return func(1, 2, 3)
end, function(err)
  print(err)
end)

success, result = pcall(func, 1, 2, 3)

xpcall(func, function(err)
  print(err)
end, 1, 2, 3)
```
