### ISSUE TITLE
Default Class Parent

### ISSUE THREAD

**Issue by 11clock** [pigpigyyy/Yuescript#86]
This is a suggestion that enables the ability to define a default class parent that will be used as the parent for classes that don't define one with "extends." This would let us customize and extend the class functionality within Yuescript itself. See the below example on how it could look. 

```
global class __defaultparent -- or whatever you want to call it
  __tostring: "I am a class!"
  
class Example

example = Example!
print example
-- outputs "I am a class!"
```

For compilation, generated code could check if "__defaultparent" exists in the current scope, and if so use that if a parent wasn't specified.

**Comment by pigpigyyy** [comment]
I got a feeling that the default parent idea is just offering a way to do an implicit inheritance. Why not just do it in a explicit way?

**Comment by 11clock** [comment]
I now think that a default mixin would work better. I implemented this myself and may make a merge request for it.
