### ISSUE TITLE
`export X as Y` syntax

### ISSUE THREAD

**Issue by pavelxdd** [pigpigyyy/Yuescript#98]
Currently `export tostring = ->` compiles to:

````lua
local _module_0 = { } 
local tostring 
tostring = function() end 
_module_0["tostring"] = tostring
return _module_0
````

The problem is it shadows the global `tostring` function.

I propose adding syntax `export tostring as my_tostring = ->` which will compile to:

````lua
local _module_0 = { }
local my_tostring 
my_tostring = function() end
_module_0["tostring"] = my_tostring
return _module_0
````

This way I can export the custom functions in modules which may have the same names as global variables.

**Comment by apologetiks** [comment]
why not do something like:

```moonscript
my_tostring = ->
  "string"

export default {
    tostring: my_tostring
}
```

**Comment by pavelxdd** [comment]
That's just a proposal. There is a `import X as Y` syntax, why not have something similar for `export`.

**Comment by pigpigyyy** [comment]
Or you may prevent shadowing global variables by place the export statement in last lines of the file?
```moonscript
my_tostring = ->
  "string"

print tostring 123

export tostring = my_tostring
```
