### ISSUE TITLE
`unless X?` syntax

### ISSUE THREAD

**Issue by pavelxdd** [pigpigyyy/Yuescript#99]
Currently `print Y unless X?` compiles to:

````lua
if not (X ~= nil) then
  return print(Y)
end
````

so we have a double negation condition here.

Is it possible to compile such code to:

````lua
if X == nil then
  return print(Y)
end
````

?

**Comment by apologetiks** [comment]
that's what `unless x` is. the `?` is operating as intended here, so why is it here?
`if not x` and `if x == nil` are equivalent. 

if you are trying to be strict, you can `if x == nil` or `unless not x?`, eg

```moonscript
x = false
unless not x?
  print "x = #{ inspect x }" -- prints "x = false"
```

but this reads awkward.

**Comment by pigpigyyy** [comment]
This is involved in compiling optimization. If we want to make a more advanced compiler we will have to take all the cases of optimizations into considerations. But for the moment this function has a lower priority to be implemented.
